language: python
python:
    "3.6"
install:
     "pip install -r requirements.txt"   
script:
     - "python tests/test_bucketlist.py"
     - "python tests/test_user.py"
     - "coverage run test_user.py"
     - "coverage run test_bucketlist.py"
after_success: coveralls
