language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch
  - "nightly"
install:
  "pip install -r requirements.txt"
  "pip install unittest2"
script:
  "python backend/test_bucketList.py"
  "python backend/test_user.py"
  "coverage run test_for_class_User.py"
after_success: coveralls