language: python
python:
    "2.7"
install:
     "pip install -r requirements.txt"   
script:
     - "python test_bucketlist.py"
     - "python test_user.py"
     - "coverage run test_user.py"
after_success: coveralls
